version: "3.7"

services:
  sphinx:
    build:
      context: ./source
      dockerfile: ../Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./source:/docs/source
      - ../flask_uploader:/python_packages/flask_uploader:ro
